source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Pin_Example', :exclusive => true do
  pod "Pin", :path => "../"
end

target 'Pin_Tests', :exclusive => true do
  pod "Pin", :path => "../"

  
end
